Jdb200503 5
pplutap/jdp-2005-03 pull request #10
Opened 2020-05-29 06:50 UTC by B3fromSuffering

-stworzyłem klasy User i UserDto
-napisałem implementacje endpointow

2020-05-29 12:12 UTC, pplutap requested changes

2020-05-29 12:12 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public Long generateKey(UserDto userDto) {
Metoda, która coś tworzy powinna mieć nagłówek POST

2020-05-29 12:12 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +public class User {
Encja zostanie utworzona w jednym z kolejnych zadań

2020-05-30 22:00 UTC, jakubG78 requested changes
- UserDto ma pola nie do końca zgodne ze specyfikacją projektu - zobacz User.spec.json w folderze `specs` projektu - brakuje Ci pól `status`  i `userKey`
- musisz usunąć konflikty - na kanale projektu w komunikatorze jest konwersacja dot. mojej walki z konfliktami https://chat.kodilla.com/group/project-jdp-2005-03?msg=72LGzC2fe7ogBidFw

2020-06-02 14:53 UTC, pplutap approved these changes

2020-06-02 17:54 UTC, jakubG78 approved these changes

2020-06-03 05:57 UTC, merged