JDP200503-27 korekta literowki w nazwie pakietu com.kodilla.ecommerce…
pplutap/jdp-2005-03 pull request #11
Opened 2020-05-29 18:11 UTC by jakubG78

…e.controler

2020-05-29 20:36 UTC, pplutap commented
Napraw proszę konflikty

2020-05-29 21:28 UTC, jakubG78 commented
Konflikty poprawione.

2020-05-30 04:39 UTC, pplutap requested changes

2020-05-30 04:39 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto getProduct(){
Metoda powinna przyjmować wartość - id produktu

2020-05-30 08:21 UTC, jakubG78 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto getProduct(){
Dodany argument metody.

2020-05-30 19:52 UTC, jakubG78 commented
kod zmieniony, konflikty usunięte

2020-05-30 19:52 UTC, closed without merging