JDP200503-4 OrderController
pplutap/jdp-2005-03 pull request #15
Opened 2020-05-31 08:52 UTC by MarcinSchmechel

- stworzyłem klasy Order i OrderDto
- napisałem implementacje do OrderController

2020-05-31 12:13 UTC, pplutap requested changes

2020-05-31 12:13 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/order/Order.java
> +public class Order {
Klasa nie jest potrzebna w tym momencie

2020-05-31 12:13 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/order/OrderController.java
> +public class OrderController {
W projekcie istnieje już klasa `com.kodilla.ecommercee.controller.OrderController`

2020-05-31 12:39 UTC, MarcinSchmechel commented on src/main/java/com/kodilla/ecommercee/order/OrderController.java
> +public class OrderController {
Ok

2020-05-31 12:39 UTC, MarcinSchmechel commented on src/main/java/com/kodilla/ecommercee/order/Order.java
> +public class Order {
Ok

2020-06-02 14:52 UTC, pplutap requested changes

2020-06-02 14:52 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/order/OrderDto.java
> +package com.kodilla.ecommercee.order;
Klasa powinna być w pakiecie https://github.com/pplutap/jdp-2005-03/tree/master/src/main/java/com/kodilla/ecommercee/domain

2020-06-03 17:17 UTC, MarcinSchmechel commented on src/main/java/com/kodilla/ecommercee/order/OrderDto.java
> +package com.kodilla.ecommercee.order;
Ok.

2020-06-03 20:32 UTC, jakubG78 approved these changes
Według mnie wszystko ok.

2020-06-04 12:39 UTC, tomysnatalia approved these changes

2020-06-04 12:54 UTC, tomysnatalia reviewed
Przepraszam, że wyskakuje z tym tak późno, ale czy nasza klasa OrderDto  nie powinna zawierać dodatkowych atrybutów, albo przynajmniej jednego z nich np.: data zamówienia, boolena (true/false) z informacją o wysyłce.

2020-06-04 20:38 UTC, MarcinSchmechel commented
@tomysnatalia możliwe, że powinna zawierać np. boolean isPlaced albo isExecuted. Bazowałem na zależnościach z wiki. Oczywiście można dodać, ale założyłbym na to oddzielne zadanie, jeżeli w późniejszym etapie dodatkowe atrybuty będą wymagane.

2020-06-05 10:39 UTC, pplutap approved these changes

2020-06-05 16:55 UTC, merged

2020-06-07 17:13 UTC, tomysnatalia commented on src/main/java/com/kodilla/ecommercee/order/OrderDto.java
> +package com.kodilla.ecommercee.order;
Marcin wydaje mi się, że podczas zmiany zapomniałeś zmienić zapisu pakietu w Twojej wersji dalej jest "package com.kodilla.ecommercee.order"  powinno być package com.kodilla.ecommercee.domain; 
Podobnie w OrderController import powinien być do pakietu "import com.kodilla.ecommercee.domain.OrderDto;"