JDP200503-12 Encja Product - implementacja
pplutap/jdp-2005-03 pull request #20
Opened 2020-06-03 21:13 UTC by MarcinSchmechel

2020-06-04 12:34 UTC, tomysnatalia approved these changes

2020-06-04 18:32 UTC, tomysnatalia approved these changes

2020-06-04 18:33 UTC, tomysnatalia commented
Brakuje jedynie argumentu String groupId w konstruktorze.

2020-06-05 10:38 UTC, pplutap approved these changes

2020-06-05 20:10 UTC, jakubG78 requested changes
nie rozumiem po co trzeci konstruktor przyjmujący tylko argument `name`? 
moim zdanie powinny zostać tylko konstruktor bez argumentów oraz konstruktor z argumentami `name` i `id`

2020-06-05 20:27 UTC, MarcinSchmechel commented
@jakubG78 są tylko 2 konstruktory. Proszę sprawdź jeszcze raz i jak coś jest to zakomentuj ten fragment w Git.

2020-06-05 20:31 UTC, jakubG78 approved these changes
Przepraszam, mój błąd musiałem coś pomieszać przy pobieraniu kodu.

2020-06-05 21:18 UTC, merged