Jdp200503 18 group tests
pplutap/jdp-2005-03 pull request #24
Opened 2020-06-14 14:20 UTC by tomysnatalia

2020-06-14 16:28 UTC, pplutap requested changes

2020-06-14 16:28 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    Long getGroupId();
Wg mnie metoda powinna przyjmować argument w postaci `productId` - groupId byłoby zwracane dla danego produktu

2020-06-14 16:28 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    public void GroupRepositorySave() {
Nazwa metody powinna być z małej litery

2020-06-16 07:29 UTC, pplutap requested changes

2020-06-16 07:29 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +        name = "Product.getProductId",
Brakuje parametru - metoda pobiera wszystkie produkty niezależnie od grupy

2020-06-16 20:07 UTC, pplutap requested changes

2020-06-16 20:07 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +        name = "Product.getProductId",
Parametr nie powinien mieć stałej wartości (1) - metoda powinna przyjmować zmienną

2020-06-16 20:07 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void setProductList(List<Product> productList) {
Brak ciałą metody

2020-06-16 20:07 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    Long getProductId();
Jaki jest cel metody?

2020-06-17 21:20 UTC, pplutap commented
Popraw proszę konflikty

2020-06-18 12:28 UTC, pplutap requested changes

2020-06-18 12:28 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/service/GroupDbService.java
> +    private ProductRepository productRepository;
`productRepository` nie jest wykorzystywane więc nie powinno tutaj istnieć

2020-06-18 12:28 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        productRepository.save(product);
Jeśli nie używamy relacji, w produkcie powinno być ustawione `groupId` z zapisanego obiektu. Dopiero po tej operacji możemy zapisać product

2020-06-18 12:53 UTC, tomysnatalia commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        productRepository.save(product);
Group group1 = new Group (1L,"Ubrania");
        groupRepository.save(group1);
        Product product = new Product("Kurtka zimowa", "...", (100), group1.getId());
        productRepository.save(product);
       
nie wiem czy dobrze zrozumiałam

2020-06-18 18:00 UTC, pplutap requested changes

2020-06-18 18:00 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +        name = "Product.getProductId",
`GROUPID = ` - nie brakuje czegoś? Mam na myśli parametr

2020-06-18 18:56 UTC, pplutap approved these changes

2020-06-18 18:56 UTC, merged