modyfikacja encji Cart
pplutap/jdp-2005-03 pull request #25
Opened 2020-06-15 20:25 UTC by jakubG78

2020-06-16 07:28 UTC, pplutap requested changes

2020-06-16 07:28 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private CartProducts cartProducts;
Encja nie powinna zawierać `CartProducts ` - w taki sposób wprowadzamy relację, której mieć nie chcemy. Wartości typu `CartProducts ` mogą być pobierane w serwisie

2020-06-17 20:52 UTC, jakubG78 commented
Zmodyfikowałem zapytanie w interfejsie `CartAndProductRepository`, dokończyłem pisanie testu `CartService`

2020-06-17 21:19 UTC, pplutap approved these changes

2020-06-17 21:19 UTC, merged