JDP200503-16 Encja Order Testy
pplutap/jdp-2005-03 pull request #32
Opened 2020-06-21 18:52 UTC by MarcinSchmechel

2020-06-21 20:58 UTC, pplutap requested changes

2020-06-21 20:58 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Long getOrderIdByCartId(@Param("cartId") Long cartId);
Domyślam się, że metoda może zwracać listę - pobierać id obiektu po obcym id.
@jakubG78 co myślisz

2020-06-21 20:58 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    <List>Long getOrderIdByUserId(@Param("userId") Long userId);
Zła składnia, `< >` w złym miejscu

2020-06-21 21:31 UTC, jakubG78 commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Long getOrderIdByCartId(@Param("cartId") Long cartId);
Wg. mnie tak jak piszesz - ta metoda może zwrócić listę obiektów typu Long.

2020-06-22 17:00 UTC, MarcinSchmechel commented
Metody:
Long getOrderIdByCartId - pobiera id zamówienia podając id koszyka (każdy koszyk wchodzi tylko w 1 zamówienie)
List<Long> getOrderIdByUserId - pobiera listę id zamówień podając id użytkownika (każdy użytkownik może mieć kilka zamówień)

2020-06-22 17:40 UTC, pplutap requested changes

2020-06-22 17:40 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Long getOrderIdByCartId(@Param("cartId") Long cartId);
@MarcinSchmechel co z tym?

2020-06-22 17:40 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +        Long orderId = orderRepository.getOrderIdByCartId(cartId);
Spróbuj uprościć za odpowiedniej metody w `orderRepository`

2020-06-22 18:57 UTC, MarcinSchmechel commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    Long getOrderIdByCartId(@Param("cartId") Long cartId);
metoda Long getOrderIdByCartId - pobiera tylko 1 id zamówienia podając id koszyka (każdy koszyk wchodzi tylko w 1 zamówienie)

2020-06-22 19:10 UTC, MarcinSchmechel commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    <List>Long getOrderIdByUserId(@Param("userId") Long userId);
Ok, poprawione.

2020-06-22 19:12 UTC, MarcinSchmechel commented on src/main/java/com/kodilla/ecommercee/service/OrderService.java
> +        Long orderId = orderRepository.getOrderIdByCartId(cartId);
Ok, uprościłem metodę getOrderIdByCartId w OrderService.

2020-06-23 05:05 UTC, pplutap approved these changes

2020-06-23 14:32 UTC, merged